"use strict";

const INTERNAL_STATUS = Object.freeze({
  RECEIVED: "RECEBIDA",
  VALIDATED: "VALIDADA",
  CUSTOMER_SYNCED: "CLIENTE_SINCRONIZADO",
  SERVICE_ORDER_CREATED: "OS_INCLUIDA",
  INVOICE_PROCESSING: "NFSE_EM_PROCESSAMENTO",
  INVOICE_ISSUED: "NFSE_EMITIDA",
  ERROR: "ERRO",
});

const EXTERNAL_STATUS = Object.freeze({
  RECEIVED: "RECEIVED",
  VALIDATED: "VALIDATED",
  CUSTOMER_SYNCED: "CUSTOMER_SYNCED",
  SERVICE_ORDER_CREATED: "SERVICE_ORDER_CREATED",
  INVOICE_PROCESSING: "INVOICE_PROCESSING",
  INVOICE_ISSUED: "INVOICE_ISSUED",
  ERROR: "ERROR",
  REVERSAL_PENDING: "REVERSAL_PENDING",
  REVERSED: "REVERSED",
});

const CALLBACK_STATUS = Object.freeze({
  NOT_REQUIRED: "NOT_REQUIRED",
  PENDING: "PENDING",
  SENT: "SENT",
  ERROR: "ERROR",
});

const REVERSAL_STATUS = Object.freeze({
  PENDING: "PENDENTE",
  COMPLETED: "CONCLUIDO",
});

const PLATFORM_ROLES = Object.freeze(["integracao-taca", "admin", "desenvolvedor"]);
const OPERATOR_ROLES = Object.freeze(["admin", "desenvolvedor"]);

module.exports = {
  CALLBACK_STATUS,
  EXTERNAL_STATUS,
  INTERNAL_STATUS,
  OPERATOR_ROLES,
  PLATFORM_ROLES,
  REVERSAL_STATUS,
};
