import { Box, Flex, Heading, SimpleGrid, Spinner, Text } from "@chakra-ui/react";
import { useQuery } from "@tanstack/react-query";
import { useOonApi } from "@oondemand/oon-core-front";

type Metrics = { emissionsToday: number; issued: number; processing: number; errors: number; callbacksPending: number; reversalsPending: number; successRate: number; averageConfirmationMs: number; throughputLastHour: number; oldestPendingAgeMs: number; };
function duration(ms: number) { if (!ms) return "0s"; const seconds = Math.round(ms / 1000); if (seconds < 60) return `${seconds}s`; const minutes = Math.round(seconds / 60); if (minutes < 60) return `${minutes}min`; return `${Math.round(minutes / 60)}h`; }
function Metric({ label, value }: { label: string; value: string | number }) { return <Box bg="white" borderWidth="1px" borderColor="#E5E9ED" borderRadius="12px" px={5} py={5} minH="112px"><Text fontSize="12px" color="gray.500" fontWeight="600">{label}</Text><Text mt={3} fontSize="30px" lineHeight="1" fontWeight="700" color="#24323A">{value}</Text></Box>; }

export function DashboardPage() {
  const { http } = useOonApi();
  const metrics = useQuery({ queryKey: ["taca", "dashboard"], queryFn: async () => (await http.get<Metrics>("/api/taca/ops/dashboard")).data, refetchInterval: 15000 });
  return <Box><Flex justify="space-between" align={{ base: "flex-start", md: "center" }} gap={4} mb={6} direction={{ base: "column", md: "row" }}><Box><Text fontSize="11px" fontWeight="700" color="brand.500" textTransform="uppercase" letterSpacing="0.08em">Operação NFS-e</Text><Heading size="lg" color="#24323A">Dashboard</Heading><Text mt={1} fontSize="13px" color="gray.500">Emissão, fila fiscal, callbacks e estornos em tempo quase real.</Text></Box>{metrics.isFetching ? <Spinner size="sm" /> : null}</Flex>{metrics.isLoading ? <Flex minH="220px" align="center" justify="center"><Spinner size="lg" /></Flex> : metrics.isError ? <Box borderWidth="1px" borderColor="red.100" bg="red.50" color="red.700" borderRadius="10px" px={4} py={3}>Não foi possível carregar os indicadores.</Box> : <SimpleGrid columns={{ base: 1, sm: 2, xl: 3 }} gap={4}><Metric label="Emissões hoje" value={metrics.data?.emissionsToday ?? 0} /><Metric label="NFS-e emitidas" value={metrics.data?.issued ?? 0} /><Metric label="Em processamento" value={metrics.data?.processing ?? 0} /><Metric label="Erros" value={metrics.data?.errors ?? 0} /><Metric label="Callbacks pendentes" value={metrics.data?.callbacksPending ?? 0} /><Metric label="Estornos aguardando" value={metrics.data?.reversalsPending ?? 0} /><Metric label="Taxa de sucesso" value={`${metrics.data?.successRate ?? 0}%`} /><Metric label="Tempo médio até confirmação" value={duration(metrics.data?.averageConfirmationMs ?? 0)} /><Metric label="Entradas na última hora" value={metrics.data?.throughputLastHour ?? 0} /><Metric label="Idade do ticket mais antigo" value={duration(metrics.data?.oldestPendingAgeMs ?? 0)} /></SimpleGrid>}</Box>;
}
